name: bmi826-project
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem=2.5.0
  - matplotlib=3.5.0
  - numpy=1.21.4
  - pandas=1.3.4
  - pip=21.2.2
  - rdkit=2021.09.2
  - scikit-learn=1.0.1
  - seaborn=0.11.2
  - pip:
    - tensorflow==2.7.0
    - tensorflow-probability==0.14.0
