name: bmi826-project
channels:
  - conda-forge
  - defaults
dependencies:
  - deepchem=2.5.0
  - matplotlib
  - numpy
  - pandas
  - pip=21.2.2
  - rdkit
  - scikit-learn
  - seaborn
  - pip:
    - tensorflow==2.4
    - tensorflow-probability
